### ISSUE TITLE
database.ymlテンプレートの修正

### ISSUE THREAD

**Issue by bishantakuma-abewadana** [belion-freee/quickstart#3]
### 経緯
`username`と`password`がついてるとherokuがなぜか記載したユーザーでログインする。
環境変数の`DATABSE_URL`があったらそっち見るはずなのに、username書いてあったらそのユーザーでログインしようとするとか謎だけど、そもそもテンプレートに記載する必要性はないから外してOK。

### 修正箇所
https://github.com/belion-freee/quickstart/blob/master/database.default.yml

**Comment by belion-freee** [comment]
Done
